### ISSUE TITLE
Not loaded

### ISSUE THREAD

**Issue by dramnauth** [Darksmurf/history.awesomify#11]
I loaded the extension into my browser but when I go to chrome://history all it shows is icons, nothing else, and nothing is clickable.

**Comment by Darksmurf** [comment]
Sorry, Thar's because I was testing a way to get favicons from each domain. I pushed to earlier, sync your repo with mine and that might fix it. Sorry for a delayed response!


On August 7, 2016, at 19:40, dramnauth <notifications@github.com> wrote:

I loaded the extension into my browser but when I go to chrome://history all it shows is icons, nothing else, and nothing is clickable.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Darksmurf/history.awesomify","title":"Darksmurf/history.awesomify","subtitle":"GitHub repository","main_image_url":"<a href="https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg">https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/Darksmurf/history.awesomify">https://github.com/Darksmurf/history.awesomify</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Not loaded (#11)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/Darksmurf/history.awesomify/issues/11">https://github.com/Darksmurf/history.awesomify/issues/11</a>"}}}

**Comment by Darksmurf** [comment]
Woops... I forgot to click the "Sync" button on Github Desktop. Try it now.

**Comment by Darksmurf** [comment]
The icons were a result of me trying out my "Domain Grouping" algorithm (more info and source code is in the wiki).

**Comment by Darksmurf** [comment]
Commented out offending line, do a pull and confirm fix.

**Comment by Darksmurf** [comment]
Can you confirm the fix? Does it still not work

**Comment by Darksmurf** [comment]
Closing issue, as no response was made.
